import {
  readdir,
  readFile,
  writeFile,
  watch as fsWatch,
  access,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const contentDir = path.join(root, "content/pages");
const outFile = path.join(root, "src/pages.generated.ts");
const watch = process.argv.includes("--watch");

function argValue(flag) {
  const i = process.argv.indexOf(flag);
  if (i < 0 || i + 1 >= process.argv.length) return "";
  return process.argv[i + 1] ?? "";
}

/** Optional: only re-parse this slug (merge into existing generated map). */
const onlySlug = (argValue("--slug") || process.env.AS_GENERATE_SLUG || "")
  .trim()
  .replace(/\.md$/i, "");

function stripFrontmatter(source) {
  const text = source.replace(/^\uFEFF/, "");
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) return { fields: {}, body: text };
  /** @type {Record<string, string>} */
  const fields = {};
  for (const line of match[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx > 0) {
      const key = line.slice(0, idx).trim();
      let value = line.slice(idx + 1).trim();
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }
      fields[key] = value;
    }
  }
  return { fields, body: match[2] };
}

function bodyAfterHeading(afterFm) {
  const heading = afterFm.match(/^#\s+(.+)$/m);
  if (!heading || heading.index === undefined) {
    return { title: null, body: afterFm };
  }
  const title = heading[1]?.trim() || null;
  const start = heading.index;
  const end = start + heading[0].length;
  let body = afterFm.slice(0, start) + afterFm.slice(end);
  if (body.startsWith("\r\n")) body = body.slice(2);
  else if (body.startsWith("\n")) body = body.slice(1);
  return { title, body };
}

function parseTitleAndBody(source) {
  const { fields, body: afterFm } = stripFrontmatter(source);
  const peeled = bodyAfterHeading(afterFm);
  const title = peeled.title || fields.title?.trim() || "Untitled";
  // Keep author blank lines — never .trim() the body.
  return { title, body: peeled.body };
}

function pageFromRaw(slug, raw) {
  if (!raw.trim()) return { title: "", body: "" };
  return parseTitleAndBody(raw);
}

async function readExistingPages() {
  try {
    await access(outFile);
    const src = await readFile(outFile, "utf8");
    const match = src.match(
      /export const pages: Record<string, GeneratedPage> = (\{\s*[\s\S]*\})\s*;?\s*$/,
    );
    if (!match?.[1]) return {};
    return JSON.parse(match[1]);
  } catch {
    return {};
  }
}

function serializePages(pages) {
  return `// Generated by scripts/generate-pages.mjs — do not edit by hand
export type GeneratedPage = { title: string; body: string };

export const pages: Record<string, GeneratedPage> = ${JSON.stringify(pages, null, 2)};
`;
}

async function generateFull() {
  const files = (await readdir(contentDir)).filter((name) =>
    name.endsWith(".md"),
  );
  /** @type {Record<string, { title: string; body: string }>} */
  const pages = {};
  for (const file of files) {
    const slug = file.replace(/\.md$/, "");
    const raw = await readFile(path.join(contentDir, file), "utf8");
    pages[slug] = pageFromRaw(slug, raw);
  }
  return pages;
}

async function generateSlug(slug) {
  if (!/^[a-z0-9-]+$/i.test(slug)) {
    throw new Error(`invalid slug: ${slug}`);
  }
  const pages = await readExistingPages();
  const file = `${slug}.md`;
  try {
    const raw = await readFile(path.join(contentDir, file), "utf8");
    pages[slug] = pageFromRaw(slug, raw);
  } catch {
    delete pages[slug];
  }
  // If map was empty (first run / missing file), fall back to full scan.
  if (!Object.keys(pages).length) return generateFull();
  return pages;
}

async function generate() {
  const pages = onlySlug ? await generateSlug(onlySlug) : await generateFull();
  const contents = serializePages(pages);
  let prev = "";
  try {
    prev = await readFile(outFile, "utf8");
  } catch {
    /* first write */
  }
  if (prev === contents) {
    console.log(
      `[generate-pages] unchanged (${Object.keys(pages).length} pages)`,
    );
    return { wrote: false, pages };
  }
  await writeFile(outFile, contents, "utf8");
  console.log(
    `[generate-pages] wrote ${Object.keys(pages).length} pages` +
      (onlySlug ? ` (slug=${onlySlug})` : "") +
      ` → src/pages.generated.ts`,
  );
  return { wrote: true, pages };
}

await generate();

if (watch) {
  console.log(`[generate-pages] watching ${contentDir}`);
  const watcher = fsWatch(contentDir);
  for await (const event of watcher) {
    if (!event.filename || !String(event.filename).endsWith(".md")) continue;
    try {
      await generate();
    } catch (err) {
      console.error("[generate-pages] failed", err);
    }
  }
}
